// releaseAudits actions
const AUDIT__TOGGLE_LOADING = 'AUDIT__TOGGLE_LOADING'
const AUDIT__ERROR_RETURNED = 'AUDIT__ERROR_RETURNED'
const AUDIT__UPDATE_DATA = 'AUDIT__UPDATE_DATA'
const CONFIG__TOGGLE_REFRESH = 'CONFIG__TOGGLE_REFRESH'
const CONFIG__TOGGLE_RELEASED = 'CONFIG__TOGGLE_RELEASED'
const FIXVERSION__UPDATE_SELECTED = 'FIXVERSION__UPDATE_SELECTED'
const FIXVERSION__UPDATE_LIST = 'FIXVERSION__UPDATE_LIST'
const FIXVERSION__TOGGLE_LOADING = 'FIXVERSION__TOGGLE_LOADING'
const FIXVERSION__ERROR_RETURNED = 'FIXVERSION__ERROR_RETURNED'
const PROJECTS__UPDATE_SELECTED = 'PROJECTS__UPDATE_SELECTED'

export const ACTIONS = {
	AUDIT__TOGGLE_LOADING,
	AUDIT__ERROR_RETURNED,
	AUDIT__UPDATE_DATA,
	CONFIG__TOGGLE_REFRESH,
	CONFIG__TOGGLE_RELEASED,
	FIXVERSION__UPDATE_SELECTED,
	FIXVERSION__UPDATE_LIST,
	FIXVERSION__TOGGLE_LOADING,
	FIXVERSION__ERROR_RETURNED,
	PROJECTS__UPDATE_SELECTED,
}

export default ACTIONS
